// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7MbpMcjblHWR9FrCcxVPiIAVkP7F2BXY',
    appId: '1:1015806969284:web:c59839bb379a7b500d9091',
    messagingSenderId: '1015806969284',
    projectId: 'employee-35b62',
    authDomain: 'employee-35b62.firebaseapp.com',
    storageBucket: 'employee-35b62.appspot.com',
    measurementId: 'G-CTBM51YX7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi3qX_GCzaN1Qtn249CgDjU40iFBZIk58',
    appId: '1:1015806969284:android:67a9dc8bfc3984950d9091',
    messagingSenderId: '1015806969284',
    projectId: 'employee-35b62',
    storageBucket: 'employee-35b62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcH-mCyRi7nEJtdo7EBP5HTzwnGP8kZDY',
    appId: '1:1015806969284:ios:8a55d92f967e75be0d9091',
    messagingSenderId: '1015806969284',
    projectId: 'employee-35b62',
    storageBucket: 'employee-35b62.appspot.com',
    iosBundleId: 'com.example.employeeList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcH-mCyRi7nEJtdo7EBP5HTzwnGP8kZDY',
    appId: '1:1015806969284:ios:737c4f3b2378b78c0d9091',
    messagingSenderId: '1015806969284',
    projectId: 'employee-35b62',
    storageBucket: 'employee-35b62.appspot.com',
    iosBundleId: 'com.example.employeeList.RunnerTests',
  );
}
